[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[context.production.environment]
  NODE_VERSION = "22"

[context.deploy-preview.environment]
  NODE_VERSION = "22"

[context.branch-deploy.environment]
  NODE_VERSION = "22"
